"""Per-million-token prices, generated by the llm-pricing skill.

Do not edit by hand: run the skill so the source page and the date move
together. A model absent from this table renders as an em dash, which is
the honest answer when no price was read from a provider page.
"""

from __future__ import annotations

PRICING_AS_OF = "2026-09-19"

# model_id: (input_per_1m, output_per_1m, currency)
PRICES: dict[str, tuple[float, float, str]] = {
    "claude-fable-5": (10.0, 50.0, "USD"),
    "claude-haiku-4-5": (1.0, 5.0, "USD"),
    "claude-opus-4-7": (5.0, 25.0, "USD"),
    "claude-opus-4-8": (5.0, 25.0, "USD"),
    "claude-sonnet-5": (2.0, 10.0, "USD"),
    "deepseek-v4-flash": (0.3, 1.2, "USD"),
    "deepseek-v4-pro": (1.32, 3.96, "USD"),
    "gemini-3.1-flash-lite": (0.25, 1.5, "USD"),
    "gemini-3.1-pro-preview": (2.0, 12.0, "USD"),
    "gemini-3.5-flash": (1.5, 9.0, "USD"),
    "gpt-5.2": (1.75, 14.0, "USD"),
    "gpt-5.4": (2.5, 15.0, "USD"),
    "gpt-5.4-mini": (0.75, 4.5, "USD"),
    "gpt-5.4-nano": (0.2, 1.25, "USD"),
    "gpt-5.5": (5.0, 30.0, "USD"),
    "gpt-5.5-pro": (30.0, 180.0, "USD"),
}


def estimate_cost(model: str, tokens_in: int, tokens_out: int) -> float | None:
    """Return the run cost, or None when the model has no known price."""
    entry = PRICES.get(model)
    if entry is None:
        return None
    price_in, price_out, _currency = entry
    return (tokens_in / 1_000_000) * price_in + (tokens_out / 1_000_000) * price_out
